server:
  port: 8081

spring:
  datasource:
    name: datasource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/vueblog?serverTimezone=GMT%2B8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource

#日志
logging:
  level:
    com.vueblog.mapper: trace

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml

shiro-redis:
  enabled: true
  redis-manager:
    host: 127.0.0.1:6379

markerhub:
  jwt:
    # 加密秘钥
    secret: f4e2e52034348f86b67cde581c0f9eb5
    # token 有效时长 ，7天 ，单位秒
    expire: 604800
    # 标头
    header: Authorization
